import React from 'react';
import {
    Home,
    Box,
    Activity,
    ArrowLeftRight,
    Users,
    Settings,
    LogOut,
    Search,
    Bell,
    Menu,
    X,
    Plus,
    Filter,
    Download,
    Trash2,
    Edit,
    Eye,
    Check,
    AlertTriangle,
    ChevronLeft,
    ChevronRight,
    MoreVertical,
    FileText,
    Truck,
    Package,
    Lock,
    Clock,
    ClipboardList,
    LogIn,
    LogOut as LogOutIcon,
    ArrowDown,
    ArrowUp,
    Sun,
    Moon,
    RotateCcw
} from 'lucide-react';

// Export icons from Lucide to be used across the app
// We can consistently usage Lucide icons which match the 'feather-icons' likely used in original
export const Icons = {
    Home,
    Inventory: Box,
    Movements: Activity,
    Transfers: ArrowLeftRight,
    Users,
    Settings,
    Logout: LogOut,
    Search,
    Bell,
    Menu,
    Close: X,
    Plus,
    Filter,
    Export: Download,
    Delete: Trash2,
    Edit,
    View: Eye,
    Check,
    Warning: AlertTriangle,
    Prev: ChevronLeft,
    Next: ChevronRight,
    ChevronRight, // Explicit export to match usage
    More: MoreVertical,
    File: FileText,
    Truck,
    Items: Package,
    Lock,
    Clock,
    History: Clock,
    Requests: ClipboardList,
    Entries: LogIn,
    Exits: LogOutIcon,
    ArrowDown,
    ArrowUp,
    Sun,
    Moon,
    LogOut, // Add direct export for component usage
    AlertTriangle, // Add direct export for component usage
    Refresh: RotateCcw,
    Trash: Trash2 // Alias for Delete
};

